# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MmQP-Q2h0p5ksAp8bNwI3Xvff8HzLEOE
"""

import json
import math
import re
from collections import defaultdict, Counter


def tokenize(text):
    return re.findall(r"\b[a-zA-Z0-9]+\b", text.lower())


def simhash(tokens):
    v = [0] * 64

    for token in tokens:
        h = hash(token)
        for i in range(64):
            bit = 1 << i
            v[i] += 1 if h & bit else -1

    fingerprint = 0
    for i in range(64):
        if v[i] > 0:
            fingerprint |= (1 << i)

    return fingerprint


def hamming(a, b):
    return bin(a ^ b).count("1")



class BM25Indexer:
    def __init__(self, k1=1.5, b=0.75):
        self.k1 = k1
        self.b = b

        self.inverted_index = defaultdict(list)
        self.doc_freq = defaultdict(int)
        self.doc_lengths = {}

        self.posts = {}
        self.num_docs = 0
        self.avg_doc_len = 0

    def add_document(self, doc_id, tokens, raw_text):
        tf = Counter(tokens)

        self.posts[doc_id] = raw_text
        self.doc_lengths[doc_id] = len(tokens)
        self.num_docs += 1

        for term, freq in tf.items():
            self.inverted_index[term].append((doc_id, freq))
            self.doc_freq[term] += 1

    def finalize(self):
        total_len = sum(self.doc_lengths.values())
        self.avg_doc_len = total_len / self.num_docs if self.num_docs else 0

    def idf(self, term):
        df = self.doc_freq.get(term, 0)
        if df == 0:
            return 0
        return math.log(1 + (self.num_docs - df + 0.5) / (df + 0.5))

    def search(self, query, top_k=10):
        query_terms = tokenize(query)
        scores = defaultdict(float)

        for term in query_terms:
            postings = self.inverted_index.get(term, [])
            idf = self.idf(term)

            for doc_id, tf in postings:
                doc_len = self.doc_lengths[doc_id]

                numerator = tf * (self.k1 + 1)
                denominator = tf + self.k1 * (
                    1 - self.b + self.b * (doc_len / self.avg_doc_len)
                )

                scores[doc_id] += idf * (numerator / denominator)

        ranked = sorted(scores.items(), key=lambda x: x[1], reverse=True)
        return ranked[:top_k]


if __name__ == "__main__":
    bm25 = BM25Indexer()

    simhash_store = {}
    dup_threshold = 1

    total = 0
    kept = 0
    dropped = 0

    with open("./data/bluesky_posts.jsonl", "r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue

            total += 1
            post = json.loads(line)

            doc_id = post["cid"]
            text = post["text"]

            tokens = tokenize(text)
            h = simhash(tokens)

            is_dup = False
            for existing_h in simhash_store.values():
                if hamming(h, existing_h) <= dup_threshold:
                    is_dup = True
                    break

            if is_dup:
                dropped += 1
                continue

            simhash_store[doc_id] = h
            bm25.add_document(doc_id, tokens, text)
            kept += 1

            if total % 10000 == 0:
                print(f"Processed: {total} | Kept: {kept} | Dropped: {dropped}")

    bm25.finalize()

    print("\nIndexing complete.")
    print(f"Total: {total}, Kept: {kept}, Dropped (duplicates): {dropped}\n")

    # SEARCH LOOP
    while True:
        q = input("Search query: ")
        results = bm25.search(q)

        for doc_id, score in results:
            print("\n---")
            print("Score:", round(score, 4))
            print("Text:", bm25.posts[doc_id])