BOT_NAME = "internship_crawler"

# BONUS PART
CONCURRENT_REQUESTS             = 16   
CONCURRENT_REQUESTS_PER_DOMAIN  = 4    

DOWNLOAD_DELAY      = 0.5   
RANDOMIZE_DOWNLOAD_DELAY = True

DEPTH_LIMIT = 6

ROBOTSTXT_OBEY = False

DOWNLOAD_TIMEOUT = 15

RETRY_TIMES = 2

COOKIES_ENABLED = False

USER_AGENT = "Mozilla/5.0 (compatible; CS172Crawler/1.0)"

AUTOTHROTTLE_ENABLED            = True
AUTOTHROTTLE_START_DELAY        = 0.5
AUTOTHROTTLE_MAX_DELAY          = 5
AUTOTHROTTLE_TARGET_CONCURRENCY = 4.0

LOG_LEVEL = "INFO"

HTTPCACHE_ENABLED = False